<?php

namespace MisionSucre\RipesBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AcademicoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AcademicoRepository extends EntityRepository
{
    public function lista()
    {
          return $this->getEntityManager()
            ->createQuery(
                'SELECT  IDENTITY(p.user) AS u, p.priNom,p.segNom, p.priApe, p.segApe, p.cedPer,
                    a.titulouniversitario
                    FROM MisionSucreRipesBundle:Persona p,MisionSucreRipesBundle:Academico a
                    WHERE a.user = p.user
                    '
            )
            ->getResult();
    }
}
