<?php

namespace MisionSucre\RipesBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ActaNotaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ActaNotaRepository extends EntityRepository
{
    public function UCVinculadasPeriodoAmbiente($idpamb)
    {
          return $this->getEntityManager()
            ->createQuery(
                'SELECT an as a,p.priNom,p.segNom, p.priApe, p.segApe, p.cedPer FROM MisionSucreRipesBundle:ActaNota an JOIN an.docente d, MisionSucreRipesBundle:Persona p
                    WHERE an.periodoacademicoambiente=:idpamb AND d.user=p.user
                '
            )
            ->setParameters(array('idpamb'=>$idpamb))->getResult();
    }
    public function UCnoVinculadasPeriodoAmbiente($idpamb,$idppnf)
    {
          return $this->getEntityManager()
            ->createQuery(
                'SELECT m FROM MisionSucreRipesBundle:Malla m
                    WHERE m.periodopnf=:idppnf AND NOT EXISTS ( SELECT an FROM MisionSucreRipesBundle:ActaNota an JOIN an.malla ma WHERE an.periodoacademicoambiente=:idpamb AND m.id=ma.id)
                '
            )
            ->setParameters(array('idpamb'=>$idpamb,'idppnf'=>$idppnf))->getResult();
    }
    
    public function existeUnidadCurricular($idpamb,$idm)
    {
          return $this->getEntityManager()
            ->createQuery(
                'SELECT an FROM MisionSucreRipesBundle:ActaNota an
                    WHERE an.periodoacademicoambiente=:idpamb AND an.malla=:idm
                '
            )
            ->setParameters(array('idpamb'=>$idpamb,'idm'=>$idm))->getResult();
    }
}
