<?php

namespace MisionSucre\RipesBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AldeaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AldeaRepository extends EntityRepository
{
    public function findAllOrderedByParroquia($id)
    {
          return $this->getEntityManager()
            ->createQuery(
                'SELECT DISTINCT a FROM MisionSucreRipesBundle:Aldea a JOIN a.parroquia p
                    WHERE p.eje = :id 
                    '
            )
            ->setParameter('id', $id)      
            ->getResult();
    }
}
