<?php

namespace MisionSucre\RipesBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * atencionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class atencionRepository extends EntityRepository
{
    public function findAllOrderedByFecha()
    {
          return $this->getEntityManager()
            ->createQuery(
                "SELECT at.id,p.cedPer AS cedula,u.id AS idusr, u.tip_usr AS tipo, CONCAT(p.priNom,' ', p.priApe) AS nombre, at.fecha, a.nombre AS aldea, a.id AS aldeaid,
                    r.name AS perfil, at.tipo, at.estatus
                    FROM MisionSucreRipesBundle:Atencion at JOIN at.user u, 
                    MisionSucreRipesBundle:Persona p, MisionSucreRipesBundle:Aldea a, MisionSucreRipesBundle:Role r
                    WHERE p.user=u.id AND r.id=u.tip_usr
                    AND
                    (
                              u.id IN 
                            ( SELECT IDENTITY(ca.user) FROM MisionSucreRipesBundle:CoordinadorAldea ca WHERE u.id=ca.user AND ca.aldea=a.id) OR
                             u.id IN 
                            ( SELECT IDENTITY(d.user) FROM MisionSucreRipesBundle:Docente d WHERE u.id=d.user AND d.aldea=a.id) OR
                            u.id IN 
                            ( SELECT IDENTITY(t.user) FROM MisionSucreRipesBundle:Triunfador t JOIN t.ambiente am WHERE u.id=t.user AND am.aldea=a.id) OR
                             u.id IN 
                            ( SELECT IDENTITY(op.user) FROM MisionSucreRipesBundle:Operario op WHERE u.id=op.user AND op.aldea=a.id)
                            )
                    ORDER BY at.fecha
                    "
            )
            ->getResult();
    }
     public function buscar($imes,$ianyo,$fmes,$fanyo,$cedula,$tipo,$estatus){
        
        if($cedula=="")
        {
            $ced = "p.cedPer LIKE '%%'";
        }
        else
            $ced = "p.cedPer LIKE '%$cedula%'";
        
        if($tipo=="")
        {
            $tip = "at.tipo LIKE '%%'";
        }
        else
            $tip = "at.tipo LIKE '%$tipo%'";
        
        if($estatus=="")
        {
            $est = "at.estatus LIKE '%%'";
        }
        else
            $est = "at.estatus LIKE '%$estatus%'";
         
        $imes+=1;
        $fmes+=1;        
        $fechainicial=date_create("$ianyo-$imes-01");
        $fechainicial=date_format($fechainicial,"Y-m-d");
        $fechafinal=date_create("$fanyo-$fmes-31");
        $fechafinal=date_format($fechafinal,"Y-m-d");
        
        return $this->getEntityManager()
            ->createQuery(
                "SELECT at.id,p.cedPer AS cedula,u.id AS idusr, u.tip_usr AS tipo, CONCAT(p.priNom,' ', p.priApe) AS nombre, at.fecha, a.nombre AS aldea, a.id AS aldeaid,
                    r.name AS perfil, at.tipo, at.estatus
                    FROM MisionSucreRipesBundle:Atencion at JOIN at.user u, 
                    MisionSucreRipesBundle:Persona p, MisionSucreRipesBundle:Aldea a, MisionSucreRipesBundle:Role r
                    WHERE p.user=u.id AND r.id=u.tip_usr
                    AND
                    (
                              u.id IN 
                            ( SELECT IDENTITY(ca.user) FROM MisionSucreRipesBundle:CoordinadorAldea ca WHERE u.id=ca.user AND ca.aldea=a.id) OR
                             u.id IN 
                            ( SELECT IDENTITY(d.user) FROM MisionSucreRipesBundle:Docente d WHERE u.id=d.user AND d.aldea=a.id) OR
                            u.id IN 
                            ( SELECT IDENTITY(t.user) FROM MisionSucreRipesBundle:Triunfador t JOIN t.ambiente am WHERE u.id=t.user AND am.aldea=a.id) OR
                             u.id IN 
                            ( SELECT IDENTITY(op.user) FROM MisionSucreRipesBundle:Operario op WHERE u.id=op.user AND op.aldea=a.id)
                            )
                     AND $ced AND $tip AND $est
                    AND at.fecha BETWEEN :fechainicial AND :fechafinal
                    ORDER BY at.fecha
                    "
            )
            ->setParameters(array('fechainicial'=> $fechainicial,'fechafinal'=> $fechafinal))      
            ->getResult();
    }
    
    public function DataPersonal($idusr)
    {
          return $this->getEntityManager()
            ->createQuery(
                "SELECT p.cedPer AS cedula,u.id AS idusr, u.tip_usr AS tipo, CONCAT(p.priNom,' ', p.priApe) AS nombre, a.nombre AS aldea, a.id AS aldeaid,
                    r.name AS perfil
                    FROM MisionSucreRipesBundle:Persona p JOIN p.user u, 
                    MisionSucreRipesBundle:Aldea a, MisionSucreRipesBundle:Role r
                    WHERE r.id=u.tip_usr AND u.id=:id
                    AND
                    (
                              u.id IN 
                            ( SELECT IDENTITY(ca.user) FROM MisionSucreRipesBundle:CoordinadorAldea ca WHERE u.id=ca.user AND ca.aldea=a.id) OR
                             u.id IN 
                            ( SELECT IDENTITY(d.user) FROM MisionSucreRipesBundle:Docente d WHERE u.id=d.user AND d.aldea=a.id) OR
                            u.id IN 
                            ( SELECT IDENTITY(t.user) FROM MisionSucreRipesBundle:Triunfador t JOIN t.ambiente am WHERE u.id=t.user AND am.aldea=a.id) OR
                             u.id IN 
                            ( SELECT IDENTITY(op.user) FROM MisionSucreRipesBundle:Operario op WHERE u.id=op.user AND op.aldea=a.id)
                            )
                    "
            )->setParameters(array('id'=> $idusr))      
            ->getSingleResult();
    }
}
