<?php

namespace MisionSucre\RipesBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EjeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EjeRepository extends EntityRepository
{
    
    public function findAllOrderedByEje($id)
    {
          return $this->getEntityManager()
            ->createQuery(
                'SELECT DISTINCT m.municipio,m.id FROM MisionSucreRipesBundle:Municipio m JOIN m.parroquias p
                    JOIN p.eje e
                    WHERE e.id = :id 
                    '
            )
            ->setParameter('id', $id)      
            ->getResult();
    }
    
    public function findAllOrderedByParroquia($id)
    {
          return $this->getEntityManager()
            ->createQuery(
                'SELECT DISTINCT p.parroquia FROM MisionSucreRipesBundle:Parroquia p
                    JOIN p.eje e
                    WHERE e.id = :id 
                    '
            )
            ->setParameter('id', $id)      
            ->getResult();
    }
    
}
