<?php

namespace MisionSucre\RipesBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EnfermedadRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EnfermedadRepository extends EntityRepository
{
    public function findByTipEnf()
    {
          return $this->getEntityManager()
            ->createQuery(
                'SELECT e.id, e.tipo_enf  FROM MisionSucreRipesBundle:Enfermedad e'
            )
            ->getResult();
    }
    
    public function findOneByTipEnf($tip)
    {
          return $this->getEntityManager()
            ->createQuery(
                'SELECT e.id, e.nombre  FROM MisionSucreRipesBundle:Enfermedad e
            WHERE e.tipo_enf = :tip '
            )
            ->setParameter('tip', $tip)        
            ->getResult();
    }
}
