<?php

namespace MisionSucre\RipesBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EstructuraActividadRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EstructuraActividadRepository extends EntityRepository
{
    public function findAllByEstructura($idstr){
        
        return $this->getEntityManager()
            ->createQuery(
                'SELECT u.id AS idusr, u.tip_usr AS tipo, p.priNom,p.segNom, p.priApe, p.segApe, p.cedPer, a.id AS id, a.fecha, a.nombre,
                    a.objetivo, a.objetivo, a.observacion, a.lugar
                    FROM MisionSucreRipesBundle:EstructuraActividad a JOIN a.responsable u,
                    MisionSucreRipesBundle:Persona p
                    WHERE p.user= u.id AND a.estructura =:idstr
                    '
            )
            ->setParameters(array('idstr'=> $idstr))      
            ->getResult();
    }
}
