<?php

namespace MisionSucre\RipesBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MallaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MallaRepository extends EntityRepository
{
    public function existeUnidadCurricular($ppnf,$uc)
    {
          return $this->getEntityManager()
            ->createQuery(
                'SELECT m FROM MisionSucreRipesBundle:Malla m
                    WHERE m.periodopnf=:ppnf AND m.uc=:uc
                '
            )
            ->setParameters(array('ppnf'=>$ppnf,'uc'=>$uc))->getResult();
    }
    public function UnidadesCurricularesporCodigo($codigos)
    {
          return $this->getEntityManager()
            ->createQuery(
                'SELECT u FROM MisionSucreRipesBundle:UnidadCurricular u
                    WHERE u.codigo IN (:codigos)
                '
            )
            ->setParameters(array('codigos'=>$codigos))->getResult();
    }
    public function findByPnf($pnf)
    {
          return $this->getEntityManager()
            ->createQuery(
                'SELECT m FROM MisionSucreRipesBundle:Malla m JOIN m.periodopnf pp JOIN pp.pnf p
                    WHERE p.pnf=:pnf
                '
            )
            ->setParameters(array('pnf'=>$pnf))->getResult();
    }
}
