<?php

namespace MisionSucre\RipesBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MiembroEstructuraRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MiembroEstructuraRepository extends EntityRepository
{
     public function findAllByEstructura($idstr){
        
        return $this->getEntityManager()
            ->createQuery(
                'SELECT u.id AS idusr, u.tip_usr AS tipo, p.priNom,p.segNom, p.priApe, p.segApe, p.cedPer, m.cargo, m.id AS idmbr
                    FROM MisionSucreRipesBundle:MiembroEstructura m JOIN m.user u,
                    MisionSucreRipesBundle:Persona p
                    WHERE p.user= u.id AND m.estructura =:idstr
                    '
            )
            ->setParameters(array('idstr'=> $idstr))      
            ->getResult();
    }
}
