<?php

namespace MisionSucre\RipesBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ParroquiaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ParroquiaRepository extends EntityRepository
{
    public function findAllOrderedByEje($ideje,$idmun)
    {
          return $this->getEntityManager()
            ->createQuery(
                'SELECT p FROM MisionSucreRipesBundle:Parroquia p
                    WHERE p.eje = :ideje AND p.municipio = :idmun
                    '
            )
            ->setParameters(array('ideje'=>$ideje,'idmun'=>$idmun))      
            ->getResult();
    }
}
