<?php

namespace MisionSucre\RipesBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PeriodoAcademicoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PeriodoAcademicoRepository extends EntityRepository
{
     public function findAll(){
    return $this->getEntityManager()
            ->createQuery(
                'SELECT p.id,p.nombre,p.fechainicio,p.fechafin,p.actual, p.modalidad,
                    ( SELECT COUNT(pa.id) FROM MisionSucreRipesBundle:PeriodoAcademicoAmbiente pa WHERE pa.periodoacademico=p.id ) as totalambiente
                    FROM MisionSucreRipesBundle:PeriodoAcademico p
                '
            )
            ->getResult();
     }
     
     public function findAllPeriodoAcademico($periodoacademico){
    return $this->getEntityManager()
            ->createQuery(
                'SELECT COUNT(pa.id) as total FROM MisionSucreRipesBundle:PeriodoAcademicoAmbiente pa WHERE pa.periodoacademico=:periodoacademico
                '
            )->setParameters(array('periodoacademico'=>$periodoacademico))
            ->getSingleResult();
     }
}
