<?php

namespace MisionSucre\RipesBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PeriodoTriunfadorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PeriodoTriunfadorRepository extends EntityRepository
{
    public function TriunfadoresVinculados($idpamb){
        
        return $this->getEntityManager()
            ->createQuery(
                'SELECT DISTINCT t.id,pt.id as idpt, u.username,p.priNom,p.segNom, p.priApe, p.segApe, p.cedPer, p.sexPer,t.condicion, u.id as idusr
                    ,p.celPer,p.telPer, t.becamision, t.sistema
                    FROM MisionSucreRipesBundle:Persona p, MisionSucreRipesBundle:User u,
                    MisionSucreRipesBundle:Triunfador t, MisionSucreRipesBundle:PeriodoTriunfador pt 
                    JOIN pt.periodoacademicoambiente ppamb JOIN ppamb.ambiente a
                    WHERE p.user=u.id AND t.user=u.id AND pt.user=u.id AND t.ambiente =a.id
                    AND ppamb.id =:idpamb
                    ORDER BY p.priNom, p.segNom
                    '
            )
            ->setParameters(array('idpamb'=>$idpamb))      
            ->getResult();
    }
    public function TriunfadoresNoVinculados($idpamb){
        
        return $this->getEntityManager()
            ->createQuery(
                'SELECT DISTINCT t.id,u.username,p.priNom,p.segNom, p.priApe, p.segApe, p.cedPer, p.sexPer,t.condicion, u.id as idusr
                    ,p.celPer,p.telPer, t.becamision, t.sistema
                    FROM MisionSucreRipesBundle:Persona p, MisionSucreRipesBundle:User u,
                    MisionSucreRipesBundle:Triunfador t,
                    MisionSucreRipesBundle:PeriodoAcademicoAmbiente ppamb JOIN ppamb.ambiente a
                    WHERE p.user=u.id AND t.user=u.id  AND t.ambiente=a.id 
                    AND 
                    NOT EXISTS (SELECT pt FROM MisionSucreRipesBundle:PeriodoTriunfador pt WHERE pt.user=u.id AND pt.periodoacademicoambiente=:idpamb )
                    ORDER BY p.priNom, p.segNom
                    '
            ) 
            ->setParameters(array('idpamb'=>$idpamb))      
            ->getResult();
    }
    public function ExisteTriunfador($idppamb,$user){
        
        return $this->getEntityManager()
            ->createQuery(
                'SELECT pt FROM  MisionSucreRipesBundle:PeriodoTriunfador pt
                    WHERE pt.user=:user AND pt.periodoacademicoambiente=:idppamb
                    '
            )
            ->setParameters(array('user'=> $user,'idppamb'=>$idppamb))      
            ->getResult();
    }
    public function ExistePeriodoAcademico($idpacad,$user){
        
        return $this->getEntityManager()
            ->createQuery(
                'SELECT pt FROM  MisionSucreRipesBundle:PeriodoTriunfador pt JOIN pt.periodoacademicoambiente paa 
                    JOIN paa.periodoacademico pacad
                    WHERE pt.user=:user AND pacad.id=:idpacad
                    '
            )
            ->setParameters(array('user'=> $user,'idpacad'=>$idpacad))      
            ->getResult();
    }
}
