<?php

namespace MisionSucre\RipesBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PeriodoAcademicoAmbienteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PeriodoAcademicoAmbienteRepository extends EntityRepository
{
    
    public function findAllByAmbiente($ambiente)
    {
          return $this->getEntityManager()
            ->createQuery(
                'SELECT pa FROM MisionSucreRipesBundle:PeriodoAcademico p, MisionSucreRipesBundle:PeriodoAcademicoAmbiente pa JOIN pa.ambiente a
                    WHERE p.actual=:actual AND a.id =:ambiente
                '
            )
            ->setParameters(array('actual'=>'SI','ambiente'=>$ambiente))->getOneOrNullResult();
    }
    public function Ambiente($ambiente)
    {
          return $this->getEntityManager()
            ->createQuery(
                'SELECT pa FROM MisionSucreRipesBundle:PeriodoAcademico p, MisionSucreRipesBundle:PeriodoAcademicoAmbiente pa JOIN pa.ambiente a
                    WHERE p.actual=:actual AND a.id =:ambiente AND
                    pa.periodoacademico=p.id
                '
            )
            ->setParameters(array('actual'=>'SI','ambiente'=>$ambiente))->getOneOrNullResult();
    }
    public function UltimoPeriodo($ambiente)
    {
          return $this->getEntityManager()
            ->createQuery(
                "SELECT pa FROM MisionSucreRipesBundle:PeriodoAcademico p, MisionSucreRipesBundle:PeriodoAcademicoAmbiente pa JOIN pa.ambiente a
                    WHERE a.id =:ambiente AND
                    pa.periodoacademico=p.id AND
                    p.nombre LIKE CONCAT('%',a.egreso)
                "
            )
            ->setParameters(array('ambiente'=>$ambiente))->getOneOrNullResult();
    }
}
