<?php

namespace MisionSucre\RipesBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PeriodoPndRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PeriodoPndRepository extends EntityRepository
{
    public function existe($pnf,$t,$p)
    {
          return $this->getEntityManager()
            ->createQuery(
                'SELECT pp FROM MisionSucreRipesBundle:PeriodoPnf pp
                    WHERE pp.pnf=:pnf AND pp.trayecto=:trayecto AND pp.periodo=:periodo
                '
            )
            ->setParameters(array('pnf'=>$pnf,'trayecto'=>$t,'periodo'=>$p))->getResult();
    }
    public function findByPnf($pnf)
    {
          return $this->getEntityManager()
            ->createQuery(
                'SELECT pp FROM MisionSucreRipesBundle:PeriodoPnf pp
                    WHERE pp.pnf=:pnf
                    ORDER BY pp.trayecto, pp.periodo
                '
            )
            ->setParameters(array('pnf'=>$pnf))->getResult();
    }
}
