<?php

namespace MisionSucre\RipesBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PersonaRepository extends EntityRepository
{
    
//    public function findOneByUser($id)
//    {
//          return $this->getEntityManager()
//            ->createQuery(
//                'SELECT u,s,m,prq,p FROM MisionSucreRipesBundle:Persona p JOIN p.user u JOIN p.sector s
//                    JOIN s.parroquia prq JOIN prq.municipio m
//                    WHERE u.id = :id 
//                    '
//            )
//            ->setParameter('id', $id)
//            ->getOneOrNullResult();
//    }
        
}

