<?php

namespace MisionSucre\RipesBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * RegistrousuarioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RegistrousuarioRepository extends EntityRepository
{
    public function CantidadporCoordinador($idcoordinador)
    {
          return $this->getEntityManager()
            ->createQuery(
                "SELECT COUNT (ru) as cantidad FROM MisionSucreRipesBundle:Registrousuario ru
                            WHERE ru.registrador=:idusr
                    "
            )
            ->setParameters(array('idusr'=> $idcoordinador))      
            ->getSingleResult();
    }
}
