<?php

namespace MisionSucre\RipesBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TIFinalizadoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TIFinalizadoRepository extends EntityRepository
{
    public function findAllOrderedByAmbiente($idamb){
        
        return $this->getEntityManager()
            ->createQuery(
                'SELECT DISTINCT t.id,u.username,p.priNom,p.segNom, p.priApe, p.segApe, p.cedPer, p.sexPer, u.id as idusr, pa.nombre
                    FROM MisionSucreRipesBundle:Persona p, MisionSucreRipesBundle:User u,
                    MisionSucreRipesBundle:TIFinalizado t join t.periodoacademico pa
                    WHERE p.user=u.id AND t.user=u.id AND t.ambiente =:idamb
                    '
            )
            ->setParameter('idamb', $idamb)      
            ->getResult();
    }
}
