<?php

namespace MisionSucre\RipesBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * VoceroRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VoceroRepository extends EntityRepository
{
    public function findAllOrderedByAmbiente($idamb){
        
        return $this->getEntityManager()
            ->createQuery(
                'SELECT DISTINCT v.id,u.username,p.priNom,p.segNom, p.priApe, p.segApe, p.cedPer, p.sexPer, u.id as idusr
                    FROM MisionSucreRipesBundle:Persona p, MisionSucreRipesBundle:User u,
                    MisionSucreRipesBundle:Vocero v 
                    WHERE p.user=u.id AND v.user=u.id AND v.ambiente =:idamb
                    '
            )
            ->setParameter('idamb', $idamb)      
            ->getOneOrNullResult();
    }
    
    public function findAllOrderedByPersona(){
        
        return $this->getEntityManager()
            ->createQuery(
                'SELECT DISTINCT v as voc,u.username,p.priNom,p.segNom, p.priApe, p.segApe, p.cedPer, p.sexPer
                    FROM MisionSucreRipesBundle:Persona p, MisionSucreRipesBundle:User u,
                    MisionSucreRipesBundle:Vocero v JOIN v.ambiente am
                    WHERE p.user=u.id AND v.user=u.id 
                    '
            )    
            ->getResult();
    }
    public function findAllOrderedByAldea($aldea){
        
        return $this->getEntityManager()
            ->createQuery(
                'SELECT DISTINCT v.id,u.username,p.priNom,p.segNom, p.priApe, p.segApe, p.cedPer, p.sexPer, u.id AS idusr
                    FROM MisionSucreRipesBundle:Persona p, MisionSucreRipesBundle:User u,
                    MisionSucreRipesBundle:Vocero v JOIN v.ambiente am 
                    WHERE p.user=u.id AND v.user=u.id AND v.ambiente =:idamb
                    '
            )
            ->setParameter('idamb', $idamb)      
            ->getResult();
    }
}
